name: Deploy to Production

on:
  push:
    branches: [dev]
  workflow_dispatch: # Для ручного запуска

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Run tests
      run: node test.js
      env:
        NODE_ENV: test

    - name: HTML validation
      run: |
        # Простая проверка что HTML файл существует и не пустой
        if [ ! -s "index.html" ]; then
          echo "❌ index.html не существует или пустой"
          exit 1
        fi
        echo "✅ HTML validation passed"

  deploy-to-prod:
    needs: test
    runs-on: ubuntu-latest
    if: success()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
    
    - name: Merge dev to prod
      run: |
        git fetch origin
        git checkout prod
        git merge origin/dev --no-ff -m "🚀 Deploy: Auto-merge from dev to prod $(date +'%Y-%m-%d %H:%M:%S')"
        git push origin prod
    
    - name: Notify success
      run: |
        echo "✅ Deployment to production completed successfully!"
        echo "Branch: ${{ github.ref }}"
        echo "Commit: ${{ github.sha }}"